---
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../vars/packages.yml"
  tasks:

    - name: Install Packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ basic_pkg }}"
    
    - name: SSH Key
      authorized_key: 
        user: root
        key: "{{ lookup('file', '{{ playbook_dir }}/../keys/id_rsa.pub') }}"

    - name: Enable FirewallD
      service: name=firewalld state=started enabled=yes

    - name: Enable Standard Ports
      firewalld: 
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 22/tcp
        - 80/tcp
        - 443/tcp
  roles:
    - geerlingguy.repo-epel
